In [ ]:
#generate a random sequence of numbers from 1-99
#generate 100000 more sequences to check to simulate player input
#check if the player inputs equal the entire initial sequence
#check if any numbers in the sequences match one or more numbers in the initial sequence
#calculate the chances of picking all five numbers
#calculate the chances of picking 1 or more numbers in combination
#it is more likely that certain numbers will be selected by users than others. add more weight to "lucky numbers" and include this in the calculations"

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import random

In [2]:
#randomly choose six winning numbers
winning_numbers = []
for x in range(6):
    x = random.randint(0,100) #choose numbers between 0 and 99 
    winning_numbers.append(x)
print(winning_numbers)

[40, 97, 47, 54, 28, 58]


In [9]:
#now, generate 1000000 more random sets to simulate players
np.random.seed(123)
for x in range(100):
    bets = (np.random.choice(100, 6)) #chooses 6 numbers between 0 and 99
    print(bets)

[66 92 98 17 83 57]
[86 97 96 47 73 32]
[46 96 25 83 78 36]
[96 80 68 49 55 67]
[ 2 84 39 66 84 47]
[61 48  7 99 92 52]
[97 85 94 27 34 97]
[76 40  3 69 64 75]
[34 58 10 22 77 18]
[15 27 30 52 70 26]
[80  6 14 75 54 71]
[ 1 43 58 55 25 50]
[84 56 49 12 18 81]
[ 1 51 44 48 56 91]
[49 86  3 67 11 21]
[89 98  3 11  3 94]
[ 6  9 87 14 83 70]
[12 54 27 38 17 61]
[74 99 99 65 47 16]
[ 5 86 46 15 59 40]
[25 45 49  0 35 29]
[ 1 83 68 30  7 93]
[60 65 76 67 44 51]
[ 7 88 70 13 28 63]
[84 36 96 40 88 63]
[58 77  8 78  6 65]
[94 70 40 74 76 76]
[25  7 13 44  1 41]
[78 56 87 63 97  3]
[17 88 87 69 97 50]
[ 2 18 46 45 57 35]
[18 91 46 54 73 81]
[62 67 11 26 92 75]
[10  3 45 58 59 23]
[25 27 57  3 99 78]
[85 59 48 56 87 87]
[ 4 69 56 60  9 66]
[33 69  9 79 28 66]
[10  3 48  3 23 91]
[55 34 37 49 87 85]
[25 17 58 66 45 10]
[ 8 96 25 99 67 65]
[ 7 70 99 97 39 82]
[92 38  5  9 40 68]
[87 21 89 50 36 44]
[92 99 83 81 61 14]
[78 23 62 28 80 24]
[15 49 80 84 90  4]
[21 32 39  1 98 82]
[90 35 58 38  1 52]


In [8]:
#checks whether any of the bets are equal to the winning numbers
needle = winning_numbers
haystack = bets
found = False
for row in haystack:
    if np.all(row == needle):
        found = True
        break
print("Found: ", found)

Found:  False
